# 项目基础配置
base_url: https://httpbin.org
# 需要进行测试的项目
# 文件级执行测试与模块级执行测试不能共存
test_project:
  # 文件级执行测试，多个文件用英文逗号隔开
  single_file:
  demo: True
  mid_admin_service:
  # 组合套餐服务，需要单独配置是否执行测试
  cw_plans_service:
  cw_plans_app_service:

base_test_config:
  Test_Report_Title: 接口自动化测试报告
  Test_Report_Generate: True  # 是否生成测试报告
  Affiliate_Service: https://mid-api-test.channelwill.com/affiliate
  Mid_Admin_Service: https://mid-api-test.channelwill.com/mid-admin
  # Loloyal服务
  Loloyal_Service_Original_Test: https://app-test.loloyal.com
  # Market服务
  Market_Service:
  # 邮件服务
  Email_Service:
  # 组合套餐
  CW_Plans_App_Service:
  # 官网地址
  CW_Plans_Service:

  # 测试账号
  # affiliate测试账号
  affiliate_test_user: ou.lee@channelwill.com
  affiliate_test_pwd: LIou6757

  # mid_admin测试账号
  mid_admin_test_user: ou.lee@channelwill.com
  mid_admin_test_pwd: LIou6757

# 邮件推送
SMTP:
  switch: False # 邮件推送开关
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_email: 2476881327@qq.com
  sender_password: pkftjpcosegveche
  recipient: [ LL, Lee ] # 收件人名称
  recipient_email: [ ou.lee@channelwill.com, leeo01040104@gmail.com ] # 收件人邮箱
  sender: Testers # 发送人名称

# 钉钉通知
DingTalk_RobotNotice:
  switch: False # 钉钉通知开关
  is_at_all: False # 是否@所有人，默认为False
  mobile: [ "18573810472" ] # 需要@的用户手机号列表
  webhook_token: "e6bc05264f668e45cb187c0876935538be3c586c72ff37e7b92cc9a76d137f94"

# 数据库配置
Database_Config:
  max_retries: 3  # 最大重试次数
  # 常规连接
  Mid_Database:
    host: middle-grounds.rwlb.rds.aliyuncs.com
    port: 3306
    user: cw_middleground_lo_test
    pwd: 52DY9IOegf9234701
    database: cw_middleground_test

  # SSH连接（示例）
  Loloyal_Database:
    ssh_host: your-ssh-host
    ssh_port: 22
    ssh_user: your-ssh-user
    # ssh_pwd 如果是一份私钥文件时，需要在配置私钥文件路径（文件存放到config目录下），如：config\xxx.pem
    ssh_pwd: /path/to/your/keyfile.pem
    db_host: localhost
    db_port: 3306
    db_pwd: your-db-password
    db_name: your-database
